function MaterialListIsotropic = importMatFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MATERIALLISTISOTROPIC = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a cell
%  array.
%
%  MATERIALLISTISOTROPIC = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MaterialListIsotropic = importfile("/home/chris/Documents/MATLAB/unitcell/DispersionCurves/MaterialList_Isotropic.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-May-2022 12:08:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["AluminumAlloy1100", "VarName2", "VarName3", "VarName4"];
opts.VariableTypes = ["char", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "AluminumAlloy1100", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "AluminumAlloy1100", "EmptyFieldRule", "auto");

% Import the data
MaterialListIsotropic = readtable(filename, opts);

%% Convert to output type
MaterialListIsotropic = table2cell(MaterialListIsotropic);
numIdx = cellfun(@(x) ~isnan(str2double(x)), MaterialListIsotropic);
MaterialListIsotropic(numIdx) = cellfun(@(x) {str2double(x)}, MaterialListIsotropic(numIdx));
end